name: Build Android Bundle

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-20.04
    permissions: 
      contents: read
    steps:
      - uses: actions/checkout@v2
        name: Checkout repository

      - name: Use Node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: "Install npm Dependencies"
        run: yarn install
        env: 
          GH_PERSONAL_ACCESS_TOKEN: ${{secrets.GH_PERSONAL_ACCESS_TOKEN}}

      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: 'release.keystore'
          encodedString: ${{ secrets.ANDROID_UPLOAD_KEYSTORE_BASE64 }}

      - name: Build Android Bundle 
        run: ./gradlew --no-daemon assembleRelease
        working-directory: android
        env:
          ANDROID_KEYSTORE_FILE: ${{ steps.decode_keystore.outputs.filePath }}
          ANDROID_UPLOAD_STORE_PASSWORD: ${{ secrets.ANDROID_UPLOAD_STORE_PASSWORD }}
          ANDROID_UPLOAD_KEY_ALIAS: ${{ secrets.ANDROID_UPLOAD_KEY_ALIAS }}
          ANDROID_UPLOAD_KEY_PASSWORD: ${{ secrets.ANDROID_UPLOAD_KEY_PASSWORD }}
        

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: android-apk
          path: 'android/app/build/outputs/apk/release/app-release.apk'