name: Build iOS IPA

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout repository

      - name: Use Node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      
      - name: "Install npm Dependencies"
        run: yarn install
        env: 
          GH_PERSONAL_ACCESS_TOKEN: ${{secrets.GH_PERSONAL_ACCESS_TOKEN}}

      - name: Build JS bundle
        run: |
          yarn react-native bundle --platform ios --dev false --entry-file index.js --bundle-output ios/main.jsbundle --assets-dest ios
        env: 
          GH_PERSONAL_ACCESS_TOKEN: ${{secrets.GH_PERSONAL_ACCESS_TOKEN}}

      - name: Install pod dependencies
        run: |
          cd ios && pod install

      - name: Build iOS IPA
        uses: yukiarrr/ios-build-action@v1.4.0
        with:
          project-path: ios/SaltySolutions.xcodeproj
          workspace-path: ios/SaltySolutions.xcworkspace
          team-id: ${{ secrets.IOS_TEAM_ID }}
          p12-base64: ${{ secrets.IOS_P12_BASE64 }}
          certificate-password: ${{ secrets.IOS_P12_PASSWORD }}
          mobileprovision-base64: ${{ secrets.IOS_MOBILEPROVISION_BASE64 }}
          code-signing-identity: App Store
          output-path: ios/output.ipa
          scheme: SaltySolutions

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ios-IPA
          path: ios/output.ipa